/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/Mutant.gltf -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    meshmesh008: THREE.SkinnedMesh
    meshmesh008_1: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    RHReference: THREE.MeshStandardMaterial
    ['Main material']: THREE.MeshStandardMaterial
    RH: THREE.MeshStandardMaterial
  }
}

type ActionName = 'CrossPunching' | 'Dying' | 'Idle' | 'Kicking' | 'Running' | 'SidePunching' | 'Slamming' | 'Stunned' | 'TakingDamage'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/Mutant.gltf') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={1.22}>
          <primitive object={nodes.mixamorigHips} />
          <group name="mesh">
            <skinnedMesh name="meshmesh008" geometry={nodes.meshmesh008.geometry} material={materials['Main material']} skeleton={nodes.meshmesh008.skeleton} />
            <skinnedMesh name="meshmesh008_1" geometry={nodes.meshmesh008_1.geometry} material={materials.RH} skeleton={nodes.meshmesh008_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Mutant.gltf')
