/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/WoodWall.gltf -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh003: THREE.Mesh
    mesh004: THREE.Mesh
    mesh005: THREE.Mesh
    geometry_0001: THREE.Mesh
    geometry_0: THREE.Mesh
    mesh: THREE.Mesh
    mesh001: THREE.Mesh
    mesh002: THREE.Mesh
    mesh006: THREE.Mesh
    mesh007: THREE.Mesh
    mesh008: THREE.Mesh
    mesh009: THREE.Mesh
    mesh010: THREE.Mesh
    mesh011: THREE.Mesh
    geometry_0002: THREE.Mesh
    geometry_0003: THREE.Mesh
    mesh012: THREE.Mesh
    mesh013: THREE.Mesh
    mesh014: THREE.Mesh
    mesh015: THREE.Mesh
    mesh016: THREE.Mesh
    mesh017: THREE.Mesh
    geometry_0004: THREE.Mesh
    geometry_0005: THREE.Mesh
    mesh018: THREE.Mesh
    mesh019: THREE.Mesh
    mesh020: THREE.Mesh
    mesh021: THREE.Mesh
    mesh022: THREE.Mesh
    mesh023: THREE.Mesh
    geometry_0006: THREE.Mesh
    geometry_0007: THREE.Mesh
  }
  materials: {
    ['base_material.003']: THREE.MeshStandardMaterial
    ['base_material.004']: THREE.MeshStandardMaterial
    ['base_material.005']: THREE.MeshStandardMaterial
    ['Material_0.001']: THREE.MeshStandardMaterial
    Material_0: THREE.MeshStandardMaterial
    base_material: THREE.MeshStandardMaterial
    ['base_material.001']: THREE.MeshStandardMaterial
    ['base_material.002']: THREE.MeshStandardMaterial
    ['base_material.006']: THREE.MeshStandardMaterial
    ['base_material.007']: THREE.MeshStandardMaterial
    ['base_material.008']: THREE.MeshStandardMaterial
    ['base_material.009']: THREE.MeshStandardMaterial
    ['base_material.010']: THREE.MeshStandardMaterial
    ['base_material.011']: THREE.MeshStandardMaterial
    ['Material_0.002']: THREE.MeshStandardMaterial
    ['Material_0.003']: THREE.MeshStandardMaterial
    ['base_material.012']: THREE.MeshStandardMaterial
    ['base_material.013']: THREE.MeshStandardMaterial
    ['base_material.014']: THREE.MeshStandardMaterial
    ['base_material.015']: THREE.MeshStandardMaterial
    ['base_material.016']: THREE.MeshStandardMaterial
    ['base_material.017']: THREE.MeshStandardMaterial
    ['Material_0.004']: THREE.MeshStandardMaterial
    ['Material_0.005']: THREE.MeshStandardMaterial
    ['base_material.018']: THREE.MeshStandardMaterial
    ['base_material.019']: THREE.MeshStandardMaterial
    ['base_material.020']: THREE.MeshStandardMaterial
    ['base_material.021']: THREE.MeshStandardMaterial
    ['base_material.022']: THREE.MeshStandardMaterial
    ['base_material.023']: THREE.MeshStandardMaterial
    ['Material_0.006']: THREE.MeshStandardMaterial
    ['Material_0.007']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/WoodWall.gltf') as GLTFResult
  return (
        <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh003.geometry} material={materials['base_material.003']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={8.85} />
      <mesh geometry={nodes.mesh004.geometry} material={materials['base_material.004']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={8.66} />
      <mesh geometry={nodes.mesh005.geometry} material={materials['base_material.005']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={8.69} />
      <mesh geometry={nodes.geometry_0001.geometry} material={materials['Material_0.001']} position={[0, 0.16, 0]} rotation={[Math.PI, 0, Math.PI]} scale={8.96} />
      <mesh geometry={nodes.geometry_0.geometry} material={materials.Material_0} position={[0, 0.16, 0]} scale={8.96} />
      <mesh geometry={nodes.mesh.geometry} material={materials.base_material} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, 0]} scale={8.69} />
      <mesh geometry={nodes.mesh001.geometry} material={materials['base_material.001']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, 0]} scale={8.66} />
      <mesh geometry={nodes.mesh002.geometry} material={materials['base_material.002']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, 0]} scale={8.85} />
      <mesh geometry={nodes.mesh006.geometry} material={materials['base_material.006']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={8.69} />
      <mesh geometry={nodes.mesh007.geometry} material={materials['base_material.007']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={8.66} />
      <mesh geometry={nodes.mesh008.geometry} material={materials['base_material.008']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={8.85} />
      <mesh geometry={nodes.mesh009.geometry} material={materials['base_material.009']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={8.85} />
      <mesh geometry={nodes.mesh010.geometry} material={materials['base_material.010']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={8.66} />
      <mesh geometry={nodes.mesh011.geometry} material={materials['base_material.011']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={8.69} />
      <mesh geometry={nodes.geometry_0002.geometry} material={materials['Material_0.002']} position={[0, 0.16, 0]} rotation={[0, -1.57, 0]} scale={8.96} />
      <mesh geometry={nodes.geometry_0003.geometry} material={materials['Material_0.003']} position={[0, 0.16, 0]} rotation={[0, 1.57, 0]} scale={8.96} />
      <mesh geometry={nodes.mesh012.geometry} material={materials['base_material.012']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={8.69} />
      <mesh geometry={nodes.mesh013.geometry} material={materials['base_material.013']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={8.66} />
      <mesh geometry={nodes.mesh014.geometry} material={materials['base_material.014']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={8.85} />
      <mesh geometry={nodes.mesh015.geometry} material={materials['base_material.015']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={8.85} />
      <mesh geometry={nodes.mesh016.geometry} material={materials['base_material.016']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={8.66} />
      <mesh geometry={nodes.mesh017.geometry} material={materials['base_material.017']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={8.69} />
      <mesh geometry={nodes.geometry_0004.geometry} material={materials['Material_0.004']} position={[0, 0.16, 0]} rotation={[0, 1.57, 0]} scale={8.96} />
      <mesh geometry={nodes.geometry_0005.geometry} material={materials['Material_0.005']} position={[0, 0.16, 0]} rotation={[0, -1.57, 0]} scale={8.96} />
      <mesh geometry={nodes.mesh018.geometry} material={materials['base_material.018']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={8.69} />
      <mesh geometry={nodes.mesh019.geometry} material={materials['base_material.019']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={8.66} />
      <mesh geometry={nodes.mesh020.geometry} material={materials['base_material.020']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={8.85} />
      <mesh geometry={nodes.mesh021.geometry} material={materials['base_material.021']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, 0]} scale={8.85} />
      <mesh geometry={nodes.mesh022.geometry} material={materials['base_material.022']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, 0]} scale={8.66} />
      <mesh geometry={nodes.mesh023.geometry} material={materials['base_material.023']} position={[0, 0.16, 0]} rotation={[Math.PI / 2, 0, 0]} scale={8.69} />
      <mesh geometry={nodes.geometry_0006.geometry} material={materials['Material_0.006']} position={[0, 0.16, 0]} rotation={[Math.PI, 0, Math.PI]} scale={8.96} />
      <mesh geometry={nodes.geometry_0007.geometry} material={materials['Material_0.007']} position={[0, 0.16, 0]} scale={8.96} />
    </group>
  )
}

useGLTF.preload('/models/WoodWall.gltf')
